name: lucifer
description: A fast, light-weight web framework in dart to provide a simple way to fulfill the needs of many modern web server this day.
version: 1.0.3
homepage: https://github.com/salkuadrat/lucifer
repo: https://github.com/salkuadrat/lucifer

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  dotenv: ^3.0.0
  mime: ^1.0.1
  mime_type: ^1.0.0
  queue: ^3.1.0+1
  logger: ^1.1.0
  http_parser: ^4.0.0
  http_status_code: ^0.0.2
  dart_jsonwebtoken: ^2.4.0
  mustache_template: ^2.0.0
  sanitize_html: ^2.0.0
  cryptography: ^2.0.2
  uuid: ^3.0.5

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
  http: ^0.13.3