name: oryn
description: A fast, light-weight web framework to provide a simple way to fulfill the needs of many modern web server these days.
version: 1.0.1
homepage: https://github.com/atrox39/Oryn
repo: https://github.com/atrox39/Oryn

environment:
  sdk: '>=2.14.0 <4.0.0'

dependencies:
  dotenv: ^3.0.0
  mime: ^1.0.1
  mime_type: ^1.0.0
  queue: ^3.1.0+1
  logger: ^1.1.0
  http_parser: ^4.0.0
  http_status_code: ^0.0.2
  dart_jsonwebtoken: ^2.4.0
  mustache_template: ^2.0.0
  sanitize_html: ^2.0.0
  cryptography: ^2.0.5
  uuid: ^3.0.5
  sqlite3: ^2.7.6

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
  http: ^0.13.3
